name: Cleanup Sample

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Code Cleanup
        uses: ./.github/actions/
        with:
          cleanup-include: "Assets/**/*.cs"
          add-paths: "Assets"